export type VenueName = 
  | "Bordelle"
  | "Yoko" 
  | "Hang"
  | "Farsides"
  | "Farsides Brossard"
  | "Muzique"
  | "Raspoutine Paris"
  | "Raspoutine LA"
  | "Raspoutine Miami"
  | "Raspoutine Dubai"
  | "Bagatelle London"
  | "Bagatelle Miami"
  | "Bagatelle Dubai"
  | "Bagatelle St Barths"
  | "Bagatelle St Tropez"
  | "Caviar Kaspia LA"
  | "Caviar Kaspia Dubai"
  | "Caviar Kaspia NY"
  | "Caviar Kaspia London"
  | "Caviar Kaspia Paris"
  | "Stk London"
  | "Stk Ibiza"
  | "Unknown Venue";