// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqgtvisxqjfntyhqkadj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZ3R2aXN4cWpmbnR5aHFrYWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTgyNjksImV4cCI6MjA1MDYzNDI2OX0.MKYnU807c015wYnHAFviHWlF07I5ucR2gc7eRsZL78w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);